// Generated by Haxe 3.4.0
(function ($hx_exports) { "use strict";
$hx_exports["namespace"] = $hx_exports["namespace"] || {};
var Test = function() { };
Test.main = function() {
	console.log("Looking for $hxglobal.namespace.Foo");
	var cls = null;
	cls = $hx_exports["namespace.Foo"];
	console.log(cls);
};
var Foo = $hx_exports["namespace"]["Foo"] = function(a) {
	console.log("Hi, " + a);
};
Foo.MyStatic = "blah";
Test.main();
})(typeof exports != "undefined" ? exports : typeof window != "undefined" ? window : typeof self != "undefined" ? self : this);
